### ISSUE TITLE
Respecto a Desarrollo.md

### ISSUE THREAD

**Issue by diegosanchez** [fiuba/algo3_proyecto_base_tp2#14]
Viendo los comentarios hechos [PR#10](https://github.com/fiuba/algo3_proyecto_base_tp2/pull/10#discussion_r698904809) entiendo que `Desarrollo.md` describe pasos para contribuir en el repositorio. Entre los contribuyentes se encuentran lxs alumnxs oficiando de _colaborador_, y los no *alumnxs*.

Este documento (`Desarrollo.md`) le proporciona datos valiosos a lxs alumnxs (aquel que quiere aprobar la materia) o le brinda información relevante al colaborador del proyecto?

Si queremos hacer sugerencias (a los alumnos) acerca de las actividades involucradas en el proceso de desarrollo (relevamiento de requisitos, análisis, diseño, construcción, pruebas y despliegue) donde la harían? A modo de ejemplos: 

- sugerencias acerca del diseño del modelo,
- sugerencias acerca de arquitectura,
- sugerencias acerca de la calidad de una prueba,
- etc. 

cc: @seblaz @tomasBustamante

**Comment by seblaz** [comment]
Según mi entendimiento `Desarrollo.md` es un lugar en el que le proporcionamos una guía a lxs alumnxs sobre como trabajar, por eso allí tenemos guías de configuración de ambiente, diagramas, etc. que les sirven a ellxs para empezar a trabajar en su tp una vez que se copian el repo. Entiendo que cualquier sugerencia como las que mencionás la podemos incluir en ese archivo, o generar uno nuevo que se encuentre linkeado desde `Desarrollo.md`.

**Comment by diegosanchez** [comment]
Ok. Al alumno, de algo 3,  le interesa https://github.com/fiuba/algo3_proyecto_base_tp2/blob/master/docs/Desarrollo.md#empaquetado y la guía https://github.com/fiuba/algo3_proyecto_base_tp2/blob/master/docs/Docker.md. 


🤔

**Comment by seblaz** [comment]
Con respecto a Docker, es una de las formas de configurar el ambiente de  desarrollo a la par de la nativa, con lo cual lxs alumnxs pueden elegir la que les parezca mejor.

Por otro lado, el empaquetado es la forma de hacer un release y generar un entregable de forma automatizada. Esta última entiendo que a lxs alumnxs les puede interesar para poder distribuir su aplicación, aunque es cierto que es una tarea más "operativa".

**Comment by diegosanchez** [comment]
Según comenta @tomasBustamante, el entiende que el proyecto base _algo3_proyecto_base_tp2_ es una plantilla agnóstica de la materia, cualquiera de sus prácticas y metodologías.

**Comment by tomasBustamante** [comment]
Sí, para mí toda documentación dentro de este repositorio debería tener exclusivamente instrucciones sobre el proyecto en sí. La guía de desarrollo está buena y la de Docker también, ya que muestra cómo levantar el proyecto.
Todas las guías tipo tutoriales de herramientas genéricas (tipo IntelliJ o PlantUML) para mí deberían ir aparte, aunque tampoco es tan importante.

**Comment by diegosanchez** [comment]
De acuerdo.

Me problema es la relación que guardan estos dos elementos: (1) template y (2) documentos accesorios. Veo que la razón de en un documento impacta, seguramente, en el templete. Ejemplo: Si documentamos una restricción el los paquetes es porque el código del template cambio. 

Dividiendo las contribuciones en diferentes repositorios es difícil mantener ambos sincronizados.

**Comment by tomasBustamante** [comment]
>_Me problema es la relación que guardan estos dos elementos: (1) template y (2) documentos accesorios. Veo que la razón cambio de en un documento impacta, seguramente, en el templete. Ejemplo: Si documentamos una restricción el los paquetes es porque el código del template cambio._
>
>_Dividiendo las contribuciones en diferentes repositorios es difícil mantener ambos sincronizados._

Sí, tal cual. Por eso digo que ese tipo de instrucciones específicas del repositorio deben quedar en el repositorio. Lo que no debería ir, por ejemplo, es una guía de cómo configurar este proyecto en IntelliJ, debido a que (a) no es necesario utilizar IntelliJ y (b) la guía no es exclusiva de este repo, sino de prácticamente cualquier proyecto Maven. Fue por eso que en su momento la extrajimos a [este otro repo](https://github.com/fiuba/instalacion_proyecto_base_tp2). Quizás podamos encontrarle un lugar mejor.

La documentación que está actualmente en este repositorio no me parece mal. A lo sumo removería algunas oraciones de más, pero es un detalle. No terminé de entender si sugerías agregar más información o menos al repositorio.

**Comment by diegosanchez** [comment]
Puntualmente (discutamos donde) distinguiría dos audiencias:

1. colaborador del repositorio,
2. Alumno de Algo3. Ejemplo: Si documentamos una restricción el los paquetes es porque el código del template cambio, restricciones de cobertura, etc.

Para (1) `Desarrollo.md` está ok.
Para (2) no utilizaría `Desarrollo.md`.
